### ISSUE TITLE
无法播放歌曲

### ISSUE THREAD

**Issue by Misaka1008632** [lolicode-org/AllMusic_Server#1]
你好！安装后无法播放歌曲！
游戏版本：1.21.1/Fabric服务端
已安装客户端/服务端
已登录/未登录都是同样的报错
服务端报错：
[16:58:32] [NekoMusic-Worker-Thread-6/ERROR]: Uncaught exception in thread "NekoMusic-Worker-Thread-6"
java.lang.NullPointerException: Cannot read field "id" because "org.lolicode.nekomusic.NekoMusic.currentMusic" is null
        at knot/org.lolicode.nekomusic.manager.MusicManager.lambda$order$1(MusicManager.java:186) ~[NekoMusic_Server-fabric-1.21-1.1.8.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]

**Comment by KoishiMoe** [comment]
配置文件发一下，我排查一下

*如果登陆了的话，记得发之前把cookie字段内容删掉

**Comment by Misaka1008632** [comment]
> 配置文件发一下，我排查一下
> 
> *如果登陆了的话，记得发之前把cookie字段内容删掉

[nekomusic.json](https://github.com/user-attachments/files/17375617/nekomusic.json)

**Comment by Misaka1008632** [comment]
> 配置文件发一下，我排查一下
> 
> *如果登陆了的话，记得发之前把cookie字段内容删掉

没事了，不知道为什么我重启了几次游戏后它就可以播放歌曲了，给您添麻烦了不好意思

**Comment by KoishiMoe** [comment]
确实有bug，我这边复现了，漏了一个判空，一会发修复

**Comment by KoishiMoe** [comment]
已修复
